Repository daengtionary/backend, pull requests merged in 2022-08, with the labels that each got.

#4 [member] 회원가입 기능 수정
  src/main/java/com/sparta/daengtionary/cotroller/MemberController.java
  src/main/java/com/sparta/daengtionary/domain/Member.java
  src/main/java/com/sparta/daengtionary/dto/request/KakaoUserInfoDto.java
  src/main/java/com/sparta/daengtionary/dto/request/MemberRequestDto.java
  src/main/java/com/sparta/daengtionary/dto/response/MemberResponseDto.java
  src/main/java/com/sparta/daengtionary/repository/MemberRepository.java
  src/main/java/com/sparta/daengtionary/service/MemberService.java
Labels: feat, refactor

#7 [map] service 구현
  build.gradle
  src/main/java/com/sparta/daengtionary/configration/QuerydslConfiguration.java
  src/main/java/com/sparta/daengtionary/cotroller/NaverSearchController.java
  src/main/java/com/sparta/daengtionary/domain/Map.java
  src/main/java/com/sparta/daengtionary/domain/MapImg.java
  src/main/java/com/sparta/daengtionary/domain/MapInfo.java
  src/main/java/com/sparta/daengtionary/dto/request/MapRequestDto.java
  src/main/java/com/sparta/daengtionary/dto/request/PageRequest.java
  src/main/java/com/sparta/daengtionary/dto/response/MapDetailResponseDto.java
  src/main/java/com/sparta/daengtionary/dto/response/MapResponseDto.java
  src/main/java/com/sparta/daengtionary/dto/response/NaverSearchResponseDto.java
  src/main/java/com/sparta/daengtionary/repository/MapImgRepository.java
  src/main/java/com/sparta/daengtionary/repository/MapInfoRepository.java
  src/main/java/com/sparta/daengtionary/repository/MapRepository.java
  src/main/java/com/sparta/daengtionary/service/AwsS3UploadService.java
  src/main/java/com/sparta/daengtionary/service/MapService.java
  src/main/java/com/sparta/daengtionary/service/NaverSearchService.java
  src/main/java/com/sparta/daengtionary/service/naverapi/NaverSearchApiClient.java
  src/main/resources/application.properties
Labels: feat, refactor

#9 [docs] gitignore 수정 #8
  .gitignore
Labels: docs

#12 [feat] TokenProvider 수정
  .gitignore
  src/main/java/com/sparta/daengtionary/jwt/TokenProvider.java
Labels: feat

#18 [refactor] MemberService adminCode 수정
  src/main/java/com/sparta/daengtionary/service/MemberService.java
Labels: refactor
